///////////////////////////////////////////////////////////
//  CodeEnum.cs
//  Implementation of the Enumeration CodeEnum
//  Generated by Enterprise Architect
//  Created on:      31-maj-2021 17:53:21
//  Original author: AB
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public enum CodeEnum : int {

	CODE_ANALOG = 1,
	CODE_DIGITAL,
	CODE_CUSTOM,
	CODE_LIMITSET,
	CODE_SINGLENODE,
	CODE_MULTIPLENODE,
	CODE_CONSUMER,
	CODE_SOURCE

}//end CodeEnum