///////////////////////////////////////////////////////////
//  Description.cs
//  Implementation of the Class Description
//  Generated by Enterprise Architect
//  Created on:      31-maj-2021 17:53:21
//  Original author: AB
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Description {

	private int dataSet;
	private int id;
	private List<Item> listaItema;

	public int DataSet { get => dataSet; set => dataSet = value; }
	public int Id { get => id; set => id = value; }
	public List<Item> ListaItema { get => listaItema; set => listaItema = value; }

	public Description(){

	}

	~Description(){

	}

}//end Description