///////////////////////////////////////////////////////////
//  Item.cs
//  Implementation of the Class Item
//  Generated by Enterprise Architect
//  Created on:      31-maj-2021 17:53:21
//  Original author: AB
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Item {

	private CodeEnum code;
	private int value;

	public Item(){

	}

	~Item(){

	}

	public CodeEnum Code { get => code; set => code = value; }
	public int Value { get => value; set => this.value = value; }
}//end Item