///////////////////////////////////////////////////////////
//  ListaDescription.cs
//  Implementation of the Class ListaDescription
//  Generated by Enterprise Architect
//  Created on:      31-maj-2021 17:53:21
//  Original author: AB
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class ListaDescription {

	public List<Description> listDescription;

	public ListaDescription(){

	}

	~ListaDescription(){

	}

}//end ListaDescription