///////////////////////////////////////////////////////////
//  WorkerProperty.cs
//  Implementation of the Class WorkerProperty
//  Generated by Enterprise Architect
//  Created on:      31-maj-2021 17:53:21
//  Original author: AB
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class WorkerProperty {

	private CodeEnum code;
	private int workerValue;
	private DateTime timeStamp;

	public WorkerProperty(CodeEnum codeEnum,int workervalues,DateTime time)
	{
		this.code = codeEnum;
		this.workerValue = workervalues;
		this.timeStamp = time;
	}
	public WorkerProperty(){}
	~WorkerProperty(){

	}
	
	public CodeEnum Code { get => code; set => code = value; }
	public int WorkerValue { get => workerValue; set => workerValue = value; }
	public DateTime TimeStamp { get => timeStamp; set => timeStamp = value; }
}//end WorkerProperty